name: Hola mundo

on: #[push] #push, pull_request mas usado - 
    push: 
        branches:
            -   master

    pull_request:
        branches:
            -   master


jobs:
    hola: #job se ejecuta dentro de ubuntu actual
        runs-on: ubuntu-latest

        steps:
            -   name: hola-step
                run: echo "Hola mundo"

            -   name: touch-file
                run: touch hola.txt

            -   name: set-text
                run: echo "hola Mundo" >> hola.txt

    other: 
        runs-on: ubuntu-latest 
        needs: [hola] # lo hace dependiente del anterior job
        steps:
            -   name: Checkout # 
                uses: actions/checkout@v4.2.0            

            -   name: touch-file
                run: touch hola.txt

            -   name: LS
                run: | # multilinea para instalar paquetes apt-get install  curl
                    echo "hola mundo"
                    cat hola.txt
                    chmod +x script.sh
                    ./script.sh 
                    


# haciendo push  a master 4 