name: Hola mundo

on: [push]

jobs:
    hola: #job se ejecuta dentro de ubuntu actual
        runs-on: ubuntu-latest

        steps:
            -   name: hola-step
                run: echo "Hola mundo"

            -   name: touch-file
                run: rouch hola.txt

            -   name: set-text
                run: echo "hola Mundo" >> hola.txt

    other: 
        runs-on: ubuntu-latest 

        steps:
            -   name: LS
                run: ls -al
