name: Hola mundo

on: #[push] #push, pull_request mas usado - 
    push: 
        branches:
            -   master

    pull_request:
        branches:
            -   master


jobs:
    hola: #job se ejecuta dentro de ubuntu actual
        runs-on: ubuntu-latest

        steps:
            -   name: hola-step
                run: echo "Hola mundo"

            -   name: touch-file
                run: touch hola.txt

            -   name: set-text
                run: echo "hola Mundo" >> hola.txt

    other: 
        runs-on: ubuntu-latest 
        needs: [hola] # lo hace dependiente del anterior job
        steps:
            -   name: Checkout # 
                uses: actions/checkout@v4.2.0
            
            -   name: Setup Node.js environment # mejor opcion para instalar node 
                uses: actions/setup-node@v4.0.4
                with:
                    node-version: latest    
                
            -   name: node-version
                run: node --version

            -   name: touch-file
                run: touch hola.txt

            -   name: LS
                run: | # multilinea para instalar paquetes apt-get install  curl
                    echo "hola mundo"
                    cat hola.txt
                    chmod +x script.sh
                    ./script.sh
                    
            -   name: PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
            
            -   name: php-version
                run : php --version
            
                    


# haciendo push  a master 4 